config/routes.rb
Rails.application.routes.draw do
  resources :cultivos
  devise_for :users
  resources :statuses
  resources :fotoperiodos
  resources :tipo_solos
  resources :tipo_sementes
  resources :especies
  resources :generos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  
  #get '/check.txt', to: proc {[200, {}, ['it_works']]}
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cultivo.rb
class Cultivo < ApplicationRecord
end

app/models/diario.rb
class Diario < ApplicationRecord
end

app/models/especie.rb
class Especie < ApplicationRecord
end

app/models/fotoperiodo.rb
class Fotoperiodo < ApplicationRecord
end

app/models/genero.rb
class Genero < ApplicationRecord
end

app/models/semente.rb
class Semente < ApplicationRecord
end

app/models/status.rb
class Status < ApplicationRecord
end

app/models/tipo_cultivo.rb
class TipoCultivo < ApplicationRecord
end

app/models/tipo_semente.rb
class TipoSemente < ApplicationRecord
end

app/models/tipo_solo.rb
class TipoSolo < ApplicationRecord
end

app/models/tipo_tecnica.rb
class TipoTecnica < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/cultivos_controller.rb
class CultivosController < ApplicationController
  before_action :set_cultivo, only: [:show, :edit, :update, :destroy]

  # GET /cultivos
  # GET /cultivos.json
  def index
    @cultivos = Cultivo.all
  end

  # GET /cultivos/1
  # GET /cultivos/1.json
  def show
  end

  # GET /cultivos/new
  def new
    @cultivo = Cultivo.new
  end

  # GET /cultivos/1/edit
  def edit
  end

  # POST /cultivos
  # POST /cultivos.json
  def create
    @cultivo = Cultivo.new(cultivo_params)

    respond_to do |format|
      if @cultivo.save
        format.html { redirect_to @cultivo, notice: 'Cultivo was successfully created.' }
        format.json { render :show, status: :created, location: @cultivo }
      else
        format.html { render :new }
        format.json { render json: @cultivo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cultivos/1
  # PATCH/PUT /cultivos/1.json
  def update
    respond_to do |format|
      if @cultivo.update(cultivo_params)
        format.html { redirect_to @cultivo, notice: 'Cultivo was successfully updated.' }
        format.json { render :show, status: :ok, location: @cultivo }
      else
        format.html { render :edit }
        format.json { render json: @cultivo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cultivos/1
  # DELETE /cultivos/1.json
  def destroy
    @cultivo.destroy
    respond_to do |format|
      format.html { redirect_to cultivos_url, notice: 'Cultivo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cultivo
      @cultivo = Cultivo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cultivo_params
      params.require(:cultivo).permit(:data_cultivo, :tipo_cultivo_id, :descricao)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 def index
 end     
    
   
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cultivos_helper.rb
module CultivosHelper
end

app/helpers/especies_helper.rb
module EspeciesHelper
end

app/helpers/fotoperiodos_helper.rb
module FotoperiodosHelper
end

app/helpers/generos_helper.rb
module GenerosHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/tipo_sementes_helper.rb
module TipoSementesHelper
end

app/helpers/tipo_solos_helper.rb
module TipoSolosHelper
end

app/views/cultivos/_form.html.erb
<%= form_for(cultivo) do |f| %>
  <% if cultivo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cultivo.errors.count, "error") %> prohibited this cultivo from being saved:</h2>

      <ul>
      <% cultivo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :data_cultivo %>
    <%= f.datetime_select :data_cultivo %>
  </div>

  <div class="field">
    <%= f.label :tipo_cultivo_id %>
    <%= f.number_field :tipo_cultivo_id %>
  </div>

  <div class="field">
    <%= f.label :descricao %>
    <%= f.text_field :descricao %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cultivos/edit.html.erb
<div class="container">



  <div class="row">
          <div class="col-md offset-md-1"><h1> Editar</h1></div>
  </div>

<%= render 'form', cultivo: @cultivo %>

<%= link_to 'Show', @cultivo %> |
<%= link_to 'Back', cultivos_path %>


  </div>

app/views/cultivos/index.html.erb
<div class="container">

<p id="notice"><%= notice %></p>

  <div class="row">
          <div class="col-md offset-md-1"><h1> Cultivos</h1></div>
  </div>

  <div class="row">
          <div class="col-md offset-md-1"><h7><b> Data Cultivo</h7></b></div>
          <div class="col-md"><h7><b> Tipo Cultivo</h7></b></div>
          <div class="col-md"><h7><b> Descrição</h7></b></div>
          <div class="col-md"><h7> </h7></div>
  </div>
 

    <% @cultivos.each do |cultivo| %>
      <div class="row">
         <div class="col-md offset-md-1"><h7><%= cultivo.data_cultivo %></h7></div>
         <div class="col-md"><h7><%= cultivo.tipo_cultivo_id %></h7></div>
         <div class="col-md"><h7><%= cultivo.descricao %></h7></div>
         <div class="col-md"><h7><%= link_to 'Ver', cultivo %>
         <%= link_to 'Editar', edit_cultivo_path(cultivo) %>
         <%= link_to 'Deletar', cultivo, method: :delete, data: { confirm: 'Are you sure?' } %></h7></div>
      </div>
    <% end %>

       
  <div class="row">         
    <div class="col-md offset-md-1"> 
      <%= link_to 'Adicionar', new_cultivo_path, class: 'btn btn-success'  %>
    </div>
  </div>
 
</div>
  

app/views/cultivos/new.html.erb
<div class="container">

<p id="notice"><%= notice %></p>

  <div class="row">
          <div class="col-md offset-md-1"><h1> Adicionar</h1></div>
  </div>

<%= render 'form', cultivo: @cultivo %>

<%= link_to 'Back', cultivos_path %>
 </div>

app/views/cultivos/show.html.erb
<div class="container">

<p id="notice"><%= notice %></p>

  <div class="row">
          <div class="col-md offset-md-1"><h1> Mostrar</h1></div>
  </div>
  
  
<p>
  <strong>Data cultivo:</strong>
  <%= @cultivo.data_cultivo %>
</p>

<p>
  <strong>Tipo cultivo:</strong>
  <%= @cultivo.tipo_cultivo_id %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @cultivo.descricao %>
</p>

<%= link_to 'Edit', edit_cultivo_path(@cultivo) %> |
<%= link_to 'Back', cultivos_path %>
  </div>