config/routes.rb
Rails.application.routes.draw do
  resources :cultivos
  devise_for :users
  resources :statuses
  resources :fotoperiodos
  resources :tipo_solos
  resources :tipo_sementes
  resources :especies
  resources :generos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  
  #get '/check.txt', to: proc {[200, {}, ['it_works']]}
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cultivo.rb
class Cultivo < ApplicationRecord
end

app/models/diario.rb
class Diario < ApplicationRecord
end

app/models/especie.rb
class Especie < ApplicationRecord
end

app/models/fotoperiodo.rb
class Fotoperiodo < ApplicationRecord
end

app/models/genero.rb
class Genero < ApplicationRecord
end

app/models/semente.rb
class Semente < ApplicationRecord
end

app/models/status.rb
class Status < ApplicationRecord
end

app/models/tipo_cultivo.rb
class TipoCultivo < ApplicationRecord
end

app/models/tipo_semente.rb
class TipoSemente < ApplicationRecord
end

app/models/tipo_solo.rb
class TipoSolo < ApplicationRecord
end

app/models/tipo_tecnica.rb
class TipoTecnica < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 def index
 end     
    
   
  
end

app/controllers/tipo_sementes_controller.rb
class TipoSementesController < ApplicationController
  before_action :set_tipo_semente, only: [:show, :edit, :update, :destroy]

  # GET /tipo_sementes
  # GET /tipo_sementes.json
  def index
    @tipo_sementes = TipoSemente.all
  end

  # GET /tipo_sementes/1
  # GET /tipo_sementes/1.json
  def show
  end

  # GET /tipo_sementes/new
  def new
    @tipo_semente = TipoSemente.new
  end

  # GET /tipo_sementes/1/edit
  def edit
  end

  # POST /tipo_sementes
  # POST /tipo_sementes.json
  def create
    @tipo_semente = TipoSemente.new(tipo_semente_params)

    respond_to do |format|
      if @tipo_semente.save
        format.html { redirect_to @tipo_semente, notice: 'Tipo semente was successfully created.' }
        format.json { render :show, status: :created, location: @tipo_semente }
      else
        format.html { render :new }
        format.json { render json: @tipo_semente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_sementes/1
  # PATCH/PUT /tipo_sementes/1.json
  def update
    respond_to do |format|
      if @tipo_semente.update(tipo_semente_params)
        format.html { redirect_to @tipo_semente, notice: 'Tipo semente was successfully updated.' }
        format.json { render :show, status: :ok, location: @tipo_semente }
      else
        format.html { render :edit }
        format.json { render json: @tipo_semente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_sementes/1
  # DELETE /tipo_sementes/1.json
  def destroy
    @tipo_semente.destroy
    respond_to do |format|
      format.html { redirect_to tipo_sementes_url, notice: 'Tipo semente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_semente
      @tipo_semente = TipoSemente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_semente_params
      params.require(:tipo_semente).permit(:descricao)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cultivos_helper.rb
module CultivosHelper
end

app/helpers/especies_helper.rb
module EspeciesHelper
end

app/helpers/fotoperiodos_helper.rb
module FotoperiodosHelper
end

app/helpers/generos_helper.rb
module GenerosHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/tipo_sementes_helper.rb
module TipoSementesHelper
end

app/helpers/tipo_solos_helper.rb
module TipoSolosHelper
end

app/views/tipo_sementes/_form.html.erb
<%= form_for(tipo_semente) do |f| %>
  <% if tipo_semente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tipo_semente.errors.count, "error") %> prohibited this tipo_semente from being saved:</h2>

      <ul>
      <% tipo_semente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descricao %>
    <%= f.text_field :descricao %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tipo_sementes/edit.html.erb
<h1>Editing Tipo Semente</h1>

<%= render 'form', tipo_semente: @tipo_semente %>

<%= link_to 'Show', @tipo_semente %> |
<%= link_to 'Back', tipo_sementes_path %>

app/views/tipo_sementes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tipo Sementes</h1>

<table>
  <thead>
    <tr>
      <th>Descricao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tipo_sementes.each do |tipo_semente| %>
      <tr>
        <td><%= tipo_semente.descricao %></td>
        <td><%= link_to 'Show', tipo_semente %></td>
        <td><%= link_to 'Edit', edit_tipo_semente_path(tipo_semente) %></td>
        <td><%= link_to 'Destroy', tipo_semente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tipo Semente', new_tipo_semente_path %>

app/views/tipo_sementes/new.html.erb
<h1>New Tipo Semente</h1>

<%= render 'form', tipo_semente: @tipo_semente %>

<%= link_to 'Back', tipo_sementes_path %>

app/views/tipo_sementes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descricao:</strong>
  <%= @tipo_semente.descricao %>
</p>

<%= link_to 'Edit', edit_tipo_semente_path(@tipo_semente) %> |
<%= link_to 'Back', tipo_sementes_path %>