config/routes.rb
Rails.application.routes.draw do
  resources :cultivos
  devise_for :users
  resources :statuses
  resources :fotoperiodos
  resources :tipo_solos
  resources :tipo_sementes
  resources :especies
  resources :generos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  
  #get '/check.txt', to: proc {[200, {}, ['it_works']]}
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cultivo.rb
class Cultivo < ApplicationRecord
end

app/models/diario.rb
class Diario < ApplicationRecord
end

app/models/especie.rb
class Especie < ApplicationRecord
end

app/models/fotoperiodo.rb
class Fotoperiodo < ApplicationRecord
end

app/models/genero.rb
class Genero < ApplicationRecord
end

app/models/semente.rb
class Semente < ApplicationRecord
end

app/models/status.rb
class Status < ApplicationRecord
end

app/models/tipo_cultivo.rb
class TipoCultivo < ApplicationRecord
end

app/models/tipo_semente.rb
class TipoSemente < ApplicationRecord
end

app/models/tipo_solo.rb
class TipoSolo < ApplicationRecord
end

app/models/tipo_tecnica.rb
class TipoTecnica < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/fotoperiodos_controller.rb
class FotoperiodosController < ApplicationController
  before_action :set_fotoperiodo, only: [:show, :edit, :update, :destroy]

  # GET /fotoperiodos
  # GET /fotoperiodos.json
  def index
    @fotoperiodos = Fotoperiodo.all
  end

  # GET /fotoperiodos/1
  # GET /fotoperiodos/1.json
  def show
  end

  # GET /fotoperiodos/new
  def new
    @fotoperiodo = Fotoperiodo.new
  end

  # GET /fotoperiodos/1/edit
  def edit
  end

  # POST /fotoperiodos
  # POST /fotoperiodos.json
  def create
    @fotoperiodo = Fotoperiodo.new(fotoperiodo_params)

    respond_to do |format|
      if @fotoperiodo.save
        format.html { redirect_to @fotoperiodo, notice: 'Fotoperiodo was successfully created.' }
        format.json { render :show, status: :created, location: @fotoperiodo }
      else
        format.html { render :new }
        format.json { render json: @fotoperiodo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fotoperiodos/1
  # PATCH/PUT /fotoperiodos/1.json
  def update
    respond_to do |format|
      if @fotoperiodo.update(fotoperiodo_params)
        format.html { redirect_to @fotoperiodo, notice: 'Fotoperiodo was successfully updated.' }
        format.json { render :show, status: :ok, location: @fotoperiodo }
      else
        format.html { render :edit }
        format.json { render json: @fotoperiodo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fotoperiodos/1
  # DELETE /fotoperiodos/1.json
  def destroy
    @fotoperiodo.destroy
    respond_to do |format|
      format.html { redirect_to fotoperiodos_url, notice: 'Fotoperiodo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fotoperiodo
      @fotoperiodo = Fotoperiodo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fotoperiodo_params
      params.require(:fotoperiodo).permit(:descricao, :horas)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 def index
 end     
    
   
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cultivos_helper.rb
module CultivosHelper
end

app/helpers/especies_helper.rb
module EspeciesHelper
end

app/helpers/fotoperiodos_helper.rb
module FotoperiodosHelper
end

app/helpers/generos_helper.rb
module GenerosHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/tipo_sementes_helper.rb
module TipoSementesHelper
end

app/helpers/tipo_solos_helper.rb
module TipoSolosHelper
end

app/views/fotoperiodos/_form.html.erb
<%= form_for(fotoperiodo) do |f| %>
  <% if fotoperiodo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fotoperiodo.errors.count, "error") %> prohibited this fotoperiodo from being saved:</h2>

      <ul>
      <% fotoperiodo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descricao %>
    <%= f.text_field :descricao %>
  </div>

  <div class="field">
    <%= f.label :horas %>
    <%= f.number_field :horas %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fotoperiodos/edit.html.erb
<h1>Editing Fotoperiodo</h1>

<%= render 'form', fotoperiodo: @fotoperiodo %>

<%= link_to 'Show', @fotoperiodo %> |
<%= link_to 'Back', fotoperiodos_path %>

app/views/fotoperiodos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fotoperiodos</h1>

<table>
  <thead>
    <tr>
      <th>Descricao</th>
      <th>Horas</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fotoperiodos.each do |fotoperiodo| %>
      <tr>
        <td><%= fotoperiodo.descricao %></td>
        <td><%= fotoperiodo.horas %></td>
        <td><%= link_to 'Show', fotoperiodo %></td>
        <td><%= link_to 'Edit', edit_fotoperiodo_path(fotoperiodo) %></td>
        <td><%= link_to 'Destroy', fotoperiodo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fotoperiodo', new_fotoperiodo_path %>

app/views/fotoperiodos/new.html.erb
<h1>New Fotoperiodo</h1>

<%= render 'form', fotoperiodo: @fotoperiodo %>

<%= link_to 'Back', fotoperiodos_path %>

app/views/fotoperiodos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descricao:</strong>
  <%= @fotoperiodo.descricao %>
</p>

<p>
  <strong>Horas:</strong>
  <%= @fotoperiodo.horas %>
</p>

<%= link_to 'Edit', edit_fotoperiodo_path(@fotoperiodo) %> |
<%= link_to 'Back', fotoperiodos_path %>